//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Craters.rc
//
#define IDD_DI_RELATED                  101
#define IDI_ICON1                       104
#define IDC_CH_RESET                    1001
#define IDC_RESET_INT                   1002
#define IDC_BU_RELATED                  1003
#define IDC_SPIN1                       1005
#define idsInsuffMemory                 1010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
