//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Universe Creation Kit.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_MYDIALOGBAR              102
#define CG_ID_VIEW_MYDIALOGBAR          103
#define IDR_MAINFRAME                   128
#define IDR_UNIVERTYPE                  129
#define IDC_NOM                         1000
#define IDC_MASSE                       1001
#define IDC_POSX                        1002
#define IDC_TYPE                        1003
#define IDC_POSY                        1004
#define IDC_POSZ                        1005
#define IDC_VX                          1006
#define IDC_VY                          1007
#define IDC_VZ                          1008
#define IDC_ROTATION                    1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
