//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tapisserie.rc
//
#define IDS_TITRE                       1
#define IDS_TIP                         2
#define IDS_TIP_ENREGISTREE             3
#define IDD_TAPISSERIE                  101
#define IDD_DIALOG1                     102
#define IDD_DIALOG2                     103
#define IDI_ICON1                       103
#define IDD_DIALOG3                     104
#define IDI_TASKBAR                     104
#define IDI_TASKBAR_CHANGE              105
#define IDD_DIALOG3_ENREG               105
#define IDR_MENU                        106
#define IDC_GENERIC1                    1000
#define IDC_MINUTES                     1000
#define IDC_LIST1                       1001
#define IDC_IMAGES                      1001
#define IDC_AJOUTER                     1002
#define IDC_BUTTON2                     1003
#define IDC_TEST                        1003
#define IDC_BUTTON3                     1004
#define IDC_SUPPRIMER                   1004
#define IDC_LISTE_ECO                   1005
#define IDC_CONFIGURER                  1006
#define IDC_RADIO2                      1008
#define IDC_RADIO3                      1009
#define IDC_TEXTE_MINUTES               1009
#define IDC_RADIO4                      1010
#define IDC_TESTER                      1010
#define IDC_RADIO5                      1011
#define IDC_RADIO6                      1012
#define IDC_RADIO7                      1013
#define F                               1014
#define ID_F_CONFIGURATION              40002
#define ID_F_CHANGERMAINTENANT          40003
#define ID_F_FERMER                     40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
