//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ECONO.RC
//
#define DEF_INIT_YPOS                   0
#define DEF_INIT_GRAVITY                3
#define DEF_INIT_VELOC                  5
#define DEF_SPEED                       50
#define ID_OLDTEXT                      100
#define ID_BITMAP                       100
#define ID_NEWTEXT                      101
#define ID_SPEED                        101
#define ID_AGAIN                        102
#define ID_XPOS                         102
#define ID_PASSWORD                     103
#define ID_YPOS                         103
#define ID_ETOLD                        104
#define ID_VELOCITY                     104
#define ID_ETNEW                        105
#define ID_GRAVITY                      105
#define ID_ETAGAIN                      106
#define ID_SOUND                        106
#define ID_ETPASSWORD                   107
#define ID_PAUSE                        107
#define ID_ICON                         108
#define ID_PASSWORDPROTECTED            108
#define ID_PASSWORDHELP                 109
#define ID_SETPASSWORD                  109
#define ID_HELP                         110
#define ID_TIMER                        200
#define IDC_NOIR                        1000
#define IDC_NB_POINTS                   1001
#define IDC_PRIORITE                    1003
#define DEF_INIT_XPOS                   -110
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
