///////////////////////////////////////////////////////////////////////////////
// LPICLASSES
// Ces classes derivees des MFC me facilitent la vie
///////////////////////////////////////////////////////////////////////////////
#ifndef __LPICLASS_H__
#define __LPICLASS_H__

class	CLPIPathName ;
class	CLPIString ;
class	CLPISablier ;

#include "LpiString.h"
#include "LpiSablier.h"
#include "LpiBitmap.h"
#include "LpiDC.h"
#include "LpiRect.h"
#include "LpiPathName.h"
#include "LpiIcone.h"
#include "LpiCouleur.h"
                  
#endif
                  
