//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Jibe96.rc
//
#define IDS_SUPPRIME_NOTE               3
#define IDS_SUPPRIME_GROUPE             4
#define IDS_CONFIRME_GROUPE_REPERTOIRE  5
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_FORMAT_VIRTUELLE_LIBRE      101
#define IDP_FAILED_TO_CREATE            102
#define IDS_NOM_GROUPE_DEFAUT           102
#define IDB_SPLASH                      103
#define IDS_RAM_LIBRE                   103
#define CG_IDS_PHYSICAL_MEM             104
#define IDS_UNITE_MO                    104
#define CG_IDS_DISK_SPACE               105
#define IDS_UNITE_KO                    105
#define CG_IDS_DISK_SPACE_UNAVAIL       106
#define IDS_SWAP_LIBRE                  106
#define IDS_SAVE_JIBE                   107
#define IDS_FILTRE_ICONES               108
#define IDS_FILTRE_RACCOURCI            109
#define IDB_LIGHTBULB                   110
#define IDD_TIP                         111
#define CG_IDS_TIPOFTHEDAY              112
#define CG_IDS_TIPOFTHEDAYMENU          113
#define CG_IDS_DIDYOUKNOW               114
#define CG_IDS_FILE_ABSENT              115
#define CG_IDP_FILE_CORRUPT             116
#define CG_IDS_TIPOFTHEDAYHELP          117
#define IDR_MAINFRAME                   128
#define IDR_EDIT                        128
#define IDR_JIBE96TYPE                  129
#define IDR_MENU_DROITE                 130
#define IDB_SIDE_BUTTON_TOP             132
#define IDD_DIALOG_NOTE                 132
#define IDB_SIDE_BUTTON_BOTTOM          133
#define IDB_SIDE_BUTTON_LEFT            134
#define IDB_SIDE_BUTTON_RIGHT           135
#define IDR_MENU_NOTE                   147
#define IDB_HORLOGE                     148
#define IDR_MENU_HORLOGE                148
#define IDB_FOND                        149
#define IDR_MENU_DISQUE                 149
#define IDB_DATE                        150
#define IDR_MENU_SEPARATEUR             150
#define IDB_DISQUE                      151
#define IDR_MENU_GROUPE                 151
#define IDD_DIALOG1                     152
#define IDI_RAMDISK                     153
#define IDI_HARDDISK                    154
#define IDI_NETWORKDISK                 155
#define IDI_FLOPPYDISK                  156
#define IDI_CDROM                       157
#define IDB_RAM                         160
#define IDD_RAM                         161
#define IDD_MEM                         162
#define IDB_MEM                         162
#define IDI_PUCE                        163
#define IDD_SWAP                        163
#define IDB_SWAP                        163
#define IDC_CURSOR                      165
#define IDD_DIALOG2                     166
#define IDI_ICON_DESSUS                 168
#define IDI_ICON_DESSOUS                169
#define IDB_SWAP16                      169
#define IDB_DATE16                      170
#define IDB_FOND16                      171
#define IDB_HORLOGE16                   172
#define IDB_MEM16                       173
#define IDB_RAM16                       174
#define IDB_DISQUE16                    175
#define IDB_SPLASH16                    176
#define IDD_PREFERENCES                 176
#define IDD_PROPS_RACCOURCI             178
#define IDR_RACCOURCI                   179
#define IDD_GROUPE                      180
#define IDR_MENU_DATE                   180
#define IDD_CHANGE_ICONE                181
#define IDR_MENU_REP                    181
#define IDR_MENU_BOUTON                 182
#define IDB_FANTOME                     184
#define IDB_TITRE16                     185
#define IDB_TITRE                       186
#define IDI_ICON1                       189
#define IDI_ICON2                       190
#define IDB_ASSOMBRIR                   190
#define IDD_SEUIL_ALARME                191
#define IDI_SURVEILLE_REP               193
#define IDI_SURVEILLE_REP1              194
#define IDD_SURVEILLE                   194
#define IDD_OPTIONS_SURVEILLE           195
#define IDD_COMMANDE                    196
#define IDI_COMMAND                     197
#define IDI_BOUTON                      198
#define IDB_BOUTON                      199
#define IDC_TEXTE                       1000
#define IDC_BULB                        1000
#define IDC_ICONES                      1001
#define IDC_STARTUP                     1001
#define IDC_FONTE                       1002
#define IDC_NEXTTIP                     1002
#define IDC_COULEUR                     1003
#define IDC_RADIO1                      1004
#define IDC_TIPSTRING                   1004
#define IDC_RADIO2                      1005
#define IDC_RADIO3                      1006
#define IDC_ALARME                      1008
#define IDC_DISQUES                     1010
#define IDC_SLIDER1                     1011
#define IDC_DISK_SPACE                  1013
#define IDC_HAUTEUR                     1014
#define IDC_SPIN1                       1015
#define IDC_DESSIN                      1016
#define IDC_PROPS                       1018
#define IDC_SAUVEGARDE                  1019
#define IDC_NOM                         1020
#define IDC_LGCOMM                      1021
#define IDC_PARCOURIR                   1022
#define IDC_ICONE                       1023
#define IDC_EDIT1                       1026
#define IDC_PCT                         1029
#define IDC_EVENEMENTS                  1030
#define IDC_FICHIERS                    1031
#define IDC_REPERTOIRES                 1032
#define IDC_ATTRIBUTS                   1033
#define IDC_TAILLE                      1034
#define IDC_DATE_MODIF                  1035
#define IDC_SOUSREP                     1036
#define IDC_COMBO1                      1037
#define IDC_LISTE_COMMANDES             1038
#define IDM_COMMANDES                   6000
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_APROPOS                      32771
#define ID_FG_ADROITE                   32772
#define ID_FG_AGAUCHE                   32773
#define ID_FG_ENHAUT                    32774
#define ID_FG_ENBAS                     32775
#define ID_HEURE                        32776
#define ID_FG_NOUVELLEICNE_DATE         32777
#define ID_FG_DATE                      32777
#define ID_FG_NOUVELLEICNE_PLACEDISQUE  32778
#define ID_PLACEDISQUE                  32778
#define ID_FG_NOUVELLEICNE_PLACEMMOIRE  32779
#define ID_FG_NOUVELLEICNE_PLACERAM     32780
#define ID_FG_NOUVELLEICNE_NOTE         32781
#define ID_PROPRIETES                   32782
#define ID_NOTE_MINIMUM                 32783
#define ID_NOTE_MOYEN                   32784
#define ID_NOTE_MAXIMUM                 32785
#define ID_SUPPRIMER                    32786
#define ID_PLUSHAUT                     32787
#define ID_PLUSBAS                      32788
#define ID_HORLOGE_ANALOGIQUE           32789
#define ID_HORLOGE_MINUTS               32790
#define ID_HORLOGE_SECONDES             32791
#define ID_SEPARATEUR                   32792
#define ID_FG_FICHIERDCHANGE            32793
#define ID_FG_PRFRENCES                 32794
#define ID_FG                           32795
#define ID_FG_CACHER                    32795
#define ID_GROUPE                       32796
#define ID_DISQUE_COULEUR               32797
#define ID_HORLOGE_CHANGERLHEURE        32801
#define ID_NOTE_COULEUR                 32808
#define ID_NOTE_ICONE                   32809
#define ID_DISQUE_EXPLORER              32810
#define ID_SURVEILLE_REP                32811
#define ID_ARRETE_ALARME                32813
#define ID_VIDE_MESSAGES                32814
#define ID_REP_OPTIONS                  32815
#define IDM_COMMANDE                    32816
#define ID_VERTICAL                     32817
#define ID_HORIZONTAL                   32818
#define IDM_BOUTON                      32819
#define ID_EXECUTER                     32820
#define IDS_TITRE_JIBE                  59142
#define IDS_SUPPRIMER                   59143
#define IDS_CREER_ICONES                61191
#define IDS_ICONES_CREEES               61192
#define IDS_CONFIRME_NOTE               61193
#define IDS_EVENEMENT                   61194
#define IDS_NOUVEAU_FICHIER             61195
#define IDS_CHANGE_ATTR                 61196
#define IDS_CHANGE_SIZE                 61197
#define IDS_CHANGE_TIME                 61198
#define IDS_CHANGE_CTIME                61199
#define IDS_CHANGE_ATIME                61200
#define IDS_FICHIER_DISPARU             61201
#define IDS_CASE_PRESERVED              61204
#define IDS_CASE_SENSITIVE              61205
#define IDS_UNICODE_ON_DISK             61206
#define IDS_PERSISTENT_ACLS             61207
#define IDS_FILE_COMPRESSION            61208
#define IDS_VOL_COMPRESSED              61209
#define IDS_FORMAT_VOLUME               61210
#define IDS_TIP_DISQUE                  61211
#define IDS_SUPPRIMER_RACCOURCI         61212
#define IDS_AIDE                        61213
#define IDS_TIP_GROUPE                  61214

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
