//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AuFeu.rc
//
#define IDI_ICON1                       103
#define IDI_ICON2                       104
#define IDB_FUMEE                       105
#define IDB_BRAISE                      106
#define IDB_BITMAP1                     107
#define IDB_CENDRES                     109
#define IDB_CENDRE1                     112
#define IDB_CENDRE2                     113
#define IDC_FUMEE                       1002
#define IDC_DISPERSION                  1003
#define IDC_SPIN_DISPERSION             1004
#define IDC_REFROID                     1005
#define IDC_MOYENNE                     1006
#define IDC_CONVECTION                  1006
#define IDC_SPIN_REFROID                1007
#define IDC_SPIN_MOYENNE                1008
#define IDC_SPIN_CONVECTION             1008
#define IDC_CHAOS                       1009
#define IDC_SPIN_CHAOS                  1010
#define IDB_REFERENCE                   2000
#define IDB_GAZ                         2001
#define IDB_PNEUS                       2002
#define IDB_REFERENCE_16                3000
#define IDB_GAZ_16                      3001
#define IDB_PNEU16                      3002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
