//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Econo.rc
//
#define IDS_UNLOCKED                    115
#define IDS_NOT_UNLOCKED                116
#define IDS_FILTRE_FICHIER              117
#define IDS_FILTRE_FICHIER_UNIVERS      118
#define IDS_UNIVERSE_FILTRE             118
#define IDS_UNIVERSE_EXTENSION          119
#define IDD_PROPPAGE_REGISTERING        132
#define IDI_LULU                        182
#define IDD_PAGE1                       216
#define IDD_PAGE2                       217
#define IDB_MASSE7                      223
#define IDB_MASSE6                      224
#define IDB_MASSE5                      226
#define IDB_MASSE1                      227
#define IDB_MASSE2                      228
#define IDB_EXPLOSION                   228
#define IDR_EXPLOSION                   228
#define IDB_MASSE3                      229
#define IDB_MASSE4                      230
#define IDB_MASSE0                      231
#define IDI_COMETE                      242
#define IDI_IMPORTANT                   243
#define IDI_AFFICHAGE                   244
#define IDI_NOMBRES                     245
#define IDI_CREATION                    246
#define IDI_MASSES                      247
#define IDI_PHYSIQUE                    248
#define IDR_DECOR0                      249
#define IDI_PRIORITE                    249
#define IDD_DEBLOCAGE                   250
#define IDR_ESPACE_FOND                 256
#define IDR_COPYRIGHT                   270
#define IDR_TOTALE                      271
#define IDI_CINEMA                      272
#define IDI_ETOILES                     273
#define IDD_PROGRESS                    273
#define IDI_REPERE                      274
#define IDI_DELETE                      275
#define IDI_LIBERATION                  276
#define IDI_3D                          277
#define IDI_G                           278
#define IDI_MIN                         279
#define IDI_MAX                         280
#define IDI_INIT                        281
#define IDI_TEMPS                       282
#define IDI_DISTANCE                    283
#define IDI_RAYON                       284
#define IDI_DELTAVMAX                   285
#define IDI_ZOOM                        286
#define IDI_TRAVELING                   287
#define IDI_FICHIER                     288
#define IDI_MASSE_0                     289
#define IDI_MASSE_1                     290
#define IDI_MASSE_2                     291
#define IDR_PALETTE                     291
#define IDI_MASSE_3                     292
#define IDI_MASSE_4                     293
#define IDI_MASSE_5                     294
#define IDI_MASSE_6                     295
#define IDI_MASSE_7                     296
#define IDI_PARAMETRES                  297
#define IDI_CAMERA                      298
#define IDI_ETOILE                      299
#define IDI_SKINFILE                    300
#define IDB_JAUGE                       300
#define IDC_PRIORITE                    1003
#define IDS_NB_MAX_CORPS                1010
#define IDS_NB_MIN_CORPS                1011
#define IDS_PHYSIQUE                    1013
#define IDC_INITIAL                     1017
#define IDC_MINIMAL                     1018
#define IDC_ENTERCODE                   1018
#define IDC_MAXIMAL                     1019
#define IDC_KEY_CODE                    1019
#define IDC_INITIAL_NOMBRE              1020
#define IDC_CODE                        1020
#define IDC_MINIMAL_NOMBRE              1021
#define IDC_MAXIMAL_NOMBRE              1022
#define IDC_G                           1034
#define IDC_DISTANCE                    1038
#define IDC_M1                          1039
#define IDC_RAYON                       1040
#define IDC_VENT                        1041
#define IDC_M0                          1041
#define IDC_COLLISION                   1042
#define IDC_TEMPS                       1043
#define IDC_CREE_COMETES                1047
#define IDC_MAX_POUSSIERES              1049
#define IDC_REPERE                      1050
#define IDC_RADIO1                      1052
#define IDC_RADIO2                      1053
#define IDC_RADIO3                      1054
#define IDC_RADIO4                      1055
#define IDC_RADIO5                      1056
#define IDC_TAILLE_MAX                  1057
#define IDC_VIE_POUSSIERES              1058
#define IDC_DISPERSION                  1059
#define IDC_SPIN_DISPERSION             1061
#define IDC_SPIN_MAX                    1062
#define IDC_LIBERATION                  1063
#define IDC_M7                          1065
#define IDC_M6                          1066
#define IDC_M3                          1067
#define IDC_M2                          1068
#define IDC_M5                          1069
#define IDC_M4                          1070
#define IDC_EFFACER                     1071
#define IDC_SPIN_LIBERATION             1076
#define IDC_FICHIER                     1078
#define IDC_PARCOURIR                   1079
#define IDC_RESOLUTION                  1081
#define IDC_RADIO_2D                    1083
#define IDC_RADIO_3D                    1084
#define IDC_SLIDER_ETOILES              1085
#define IDC_SLIDER_IMAGES               1086
#define IDC_SLIDER_ZOOM                 1089
#define IDC_SLIDER_TRAVELLING           1090
#define IDC_MODELE                      1091
#define IDC_MODEL                       1092
#define IDC_SAUVER                      1095
#define IDC_CHARGER                     1096
#define IDC_DEFAUT                      1097
#define IDC_COMPILATION_DATE            1098
#define IDC_RADIO6                      1099
#define IDC_INTERNET                    1102
#define IDC_TREE1                       1103
#define IDC_TIP                         1104
#define IDC_INT_NUMBER                  1106
#define IDC_INT_CURRENT_VALUE           1107
#define IDC_BOOLCHECK                   1108
#define IDC_FLOTTANT_EDIT               1109
#define IDC_FLOTTANT_UNITE              1110
#define IDC_CHOIX                       1111
#define IDC_FICHIER_EDIT                1112
#define IDC_FICHIER_BROWSE              1113
#define IDC_SHAREWARE                   1116
#define IDC_PROGRESS1                   1118
#define IDC_MESSAGE                     1119
#define IDD_PAGE5                       2005
#define IDD_PAGE_COMETE                 2006
#define IDD_PAGE_PHYSIQUE               2007
#define IDD_PAGE_AFFICHAGE              2008
#define IDD_PAGE_MASSES                 2009
#define IDD_PRIORITE                    2010
#define IDD_PARAMETRES                  2011
#define IDR_PLANETS0                    3000
#define IDR_PLANETS1                    3001
#define IDR_PLANETS2                    3002
#define IDR_PLANETS3                    3003
#define IDR_PLANETS4                    3004
#define IDR_PLANETS5                    3005
#define IDR_PLANETS6                    3006
#define IDR_PLANETS7                    3007
#define IDR_DIB0                        4000
#define IDR_DIB1                        4001
#define IDR_DIB2                        4002
#define IDR_DIB3                        4003
#define IDR_DIB4                        4004
#define IDR_DIB5                        4005
#define IDR_DIB6                        4006
#define IDS_DUST_LIFE_LENGTH            5039
#define IDR_DECOR1                      7000
#define IDR_DECOR2                      7001
#define IDR_DECOR3                      7002
#define IDR_DECOR4                      7003
#define IDR_DECOR5                      7004
#define IDR_DECOR6                      7005
#define IDR_DECOR7                      7006
#define IDR_DECOR8                      7007
#define IDR_DECOR9                      7008
#define IDR_DECOR10                     7009
#define IDR_DECOR11                     7010
#define IDS_AFFICHE_REPERE              61011
#define IDS_OUI                         61012
#define IDS_NON                         61013
#define IDS_TROP_TARD                   61716
#define IDS_MESSAGE_SHAREWARE           61717
#define IDS_TITRE                       61718
#define IDS_TITRE_SETTINGS              61719
#define IDS_MAIN_SECTION                61720
#define IDS_3D                          61721
#define IDS_AFFICHER_REPERE             61722
#define IDS_BRUIT_POUSSIERES            61723
#define IDS_CHANGE_RESOLUTION           61724
#define IDS_COEFF_LIBERATION            61725
#define IDS_COEFF_TRAVELING             61726
#define IDS_CREATION_COMETE             61727
#define IDS_DELTAVMAX                   61728
#define IDS_DENSITE_ETOILES             61729
#define IDS_DEPART                      61730
#define IDS_DISTANCE_MAX                61731
#define IDS_EFFACER                     61732
#define IDS_G                           61733
#define IDS_INTERVALLE_TEMPS            61734
#define IDS_NBIMAGES_SECONDES           61735
#define IDS_NB_MAX_POUSSIERES           61736
#define IDS_TAILLE_POUSSIERES           61737
#define IDS_VENT_SOLAIRE                61738
#define IDS_VIE_POUSSIERES              61739
#define IDS_ZOOM_MAX                    61740
#define IDS_COEFF_DISTANCE              61741
#define IDS_COEFF_RAYON                 61742
#define IDS_DELTA_T_MAX                 61743
#define IDS_NB_INIT_CORPS               61744
#define IDS_MASSES_SECTION              61745
#define IDS_MASSE_0                     61746
#define IDS_MASSE_FORMAT                61746
#define IDS_MASSE_1                     61747
#define IDS_MASSE_2                     61748
#define IDS_MASSE_3                     61749
#define IDS_MASSE_4                     61750
#define IDS_MASSE_5                     61751
#define IDS_MASSE_6                     61752
#define IDS_MASSE_7                     61753
#define IDS_PRIORITE_THREAD             61754
#define IDS_NOIRCIR_ECRAN               61755
#define IDS_FORMATPLANET                61756
#define IDS_MASSE                       61757
#define IDS_POSITION                    61758
#define IDS_VITESSE                     61759
#define IDS_ORBITE                      61760
#define IDS_DISTANCE                    61761
#define IDS_ROTATION                    61762
#define IDS_BRUITPOUSSIERE              61763
#define IDS_MODELE_PHYSIQUE             61764
#define IDS_MASSES                      61765
#define IDS_COMETES                     61766
#define IDS_AFFICHAGE                   61767
#define IDS_NUMBERS                     61768
#define IDS_MIN_NUMBER                  61769
#define IDS_MAX_NUMBER                  61770
#define IDS_INIT_NUMBER                 61771
#define IDS_IMAGE_SECONDE               61772
#define IDS_DENSITEETOILES              61773
#define IDS_CHECK_DISPLAY_CROSSHAIR     61774
#define IDS_EFFACE_TRAJECTOIRES         61775
#define IDS_CHECK_EFFACE_TRAJECTOIRES   61776
#define IDS_CHANGER_RESOLUTION          61777
#define IDS_CHECK_CHANGE_RESOLUTION     61778
#define IDS_VITESSE_LIBERATION          61779
#define IDS_PHYS                        61780
#define IDS_3D2D                        61781
#define IDS_CHECK_3D2D                  61782
#define IDS_G_CST                       61783
#define IDS_COEFF_TEMPS                 61784
#define IDS_ERREUR_G                    61785
#define IDS_ERREUR_TEMPS                61786
#define IDS_COEF_DISTANCE               61787
#define IDS_COEF_RAYON                  61788
#define IDS_VITESSE_COLISION            61789
#define IDS_ERREUR_DISTANCE             61790
#define IDS_ERREUR_RAYON                61791
#define IDS_TRAVELING                   61792
#define IDS_ZOOM                        61793
#define IDS_CREATION_CHOIX              61794
#define IDS_CREATION                    61795
#define IDS_CREATION_METHOD             61796
#define IDS_FICHIER                     61797
#define IDS_SECTION_MASSES              61798
#define IDS_MASSE_ITEM                  61799
#define IDS_ERREUR_MASSE                61800
#define IDS_SECTION_COMETES             61801
#define IDS_VENTSOLAIRE                 61802
#define IDS_MAX_POUSSIERE               61803
#define IDS_TAILLE_POUSSIERE            61804
#define IDS_DISPERSION_POUSSIERE        61805
#define IDS_CREATIONCOMETE              61806
#define IDS_SHAREWARE_WND               61807
#define IDS_HTMLHELP                    61808
#define IDS_HELPFILENAME                61809
#define IDS_TITRE_ARBRE                 61810
#define IDS_SECTION_IMAGES              61811
#define IDS_FORMAT_IMAGE_FILE           61812
#define IDS_NB_IMAGES                   61813
#define IDS_INDICE_COMETE               61814
#define IDS_DUST_LIFE                   61815
#define IDS_NB_TRANSPARENCE             61816
#define IDS_NB_DECORS                   61817
#define IDS_NOM_PALETTE                 61818
#define IDS_AFFICHE_INFOS               61819
#define IDS_CHECK_AFFICHE_INFOS         61820
#define IDS_CAMERA                      61821
#define IDS_PLUSDETOILE                 61822
#define IDS_CHECK_PLUSDETOILE           61823
#define IDS_USE_SKIN_FILE               61824
#define IDS_SKIN_FILE                   61825
#define IDS_CHECK_USE_SKIN_FILE         61826
#define IDS_SKIN_EXTENSION              61827
#define IDS_SKIN_FILTRE                 61828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
