//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DELABRE.RC
//
#define IDB_APROPOS                     5
#define IDD_DIALOG1                     101
#define IDD_APROPOS                     106
#define IDC_RAPIDITE                    1000
#define IDC_GROSSEUR                    1001
#define IDC_DENSITE                     1003
#define IDC_PRIORITE                    1004
#define IDC_APROPOS                     1005
#define IDB_BITMAP1                     2000
#define IDB_BITMAP2                     2001
#define IDB_BITMAP3                     2002
#define IDB_BITMAP4                     2003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
