//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AUTOSCR.RC
//
#define IDB_APROPOS                     5
#define IDI_ICON1                       101
#define IDD_APROPOS                     106
#define IDC_ETATS                       500
#define IDC_NB_ETAT                     501
#define IDC_GRILLE                      600
#define IDC_NB_GRILLE                   601
#define IDC_COULEURS                    1000
#define IDC_APROPOS                     1001
#define DLG_SCRNSAVECONFIGURE           2003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
