//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Animation.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ANIMATION_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_ANIMATTYPE                  129
#define IDC_LISTE                       1000
#define IDC_ANIMATION                   1004
#define ID_EDITION_MONTERLIMAGE         32771
#define ID_EDITION_DESCENDRELIMAGE      32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
