//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Econo.rc
//
#define DEF_INIT_YPOS                   0
#define DEF_INIT_GRAVITY                3
#define DEF_INIT_VELOC                  5
#define DEF_SPEED                       50
#define ID_OLDTEXT                      100
#define ID_BITMAP                       100
#define ID_NEWTEXT                      101
#define ID_SPEED                        101
#define ID_AGAIN                        102
#define ID_XPOS                         102
#define ID_PASSWORD                     103
#define ID_YPOS                         103
#define ID_ETOLD                        104
#define ID_VELOCITY                     104
#define ID_ETNEW                        105
#define ID_GRAVITY                      105
#define ID_ETAGAIN                      106
#define ID_SOUND                        106
#define ID_ETPASSWORD                   107
#define ID_PAUSE                        107
#define ID_ICON                         108
#define ID_PASSWORDPROTECTED            108
#define ID_PASSWORDHELP                 109
#define ID_SETPASSWORD                  109
#define IDI_ICON1                       114
#define IDI_LPI                         181
#define IDB_BLEU                        182
#define IDB_ROUGE                       183
#define IDR_DIB1                        191
#define IDR_DIB2                        192
#define IDR_DIB3                        193
#define IDR_DIB4                        194
#define IDR_DIB5                        195
#define IDR_DIB6                        196
#define IDR_DIB7                        197
#define IDR_DIB8                        198
#define ID_TIMER                        200
#define IDB_PARTICULES                  216
#define IDD_PAGE1                       223
#define IDD_PAGE2                       224
#define IDC_NOIR                        1000
#define IDC_MAXIMAL                     1000
#define IDC_NB_POINTS                   1001
#define IDC_PRIORITE                    1003
#define IDC_RAPIDE                      1006
#define IDC_APPLIQUER                   1007
#define IDC_EXEMPLE                     1008
#define IDC_PAYSAGE                     1009
#define IDC_NBARBRES                    1010
#define IDS_NB_MAX_CORPS                1010
#define IDC_NB_CORPS                    1011
#define IDS_NB_MIN_CORPS                1011
#define IDC_MIN                         1012
#define IDS_NB_INIT                     1012
#define IDC_MAX                         1013
#define IDC_AFFICHERTROUNOIR            1016
#define IDC_INITIAL                     1017
#define IDC_MINIMAL                     1018
#define IDC_INITIAL_NOMBRE              1020
#define IDC_MINIMAL_NOMBRE              1021
#define IDC_GENERIC1                    1027
#define IDC_BUDDY1                      1027
#define IDC_PROGRESS                    1027
#define IDC_NB_PARTICULES               1028
#define IDC_NB_CHARGES                  1029
#define IDC_BUDDY2                      1030
#define IDC_RADIO_16                    1031
#define IDC_RADIO_64K                   1033
#define IDC_VITESSE                     1038
#define IDC_COULEURS                    2000
#define BITMAP64K                       2000
#define BITMAP256                       3000
#define BITMAP16                        4000
#define DEF_INIT_XPOS                   -110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
