//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mosaique.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MOSAIQUE_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_MOSAIQTYPE                  129
#define IDC_BORDURE                     1000
#define IDC_NOMDEFICHIER                1001
#define IDC_NBLIGNES                    1002
#define IDC_NBCOLONNES                  1003
#define IDC_SPIN1                       1004
#define IDC_SPIN2                       1005
#define IDC_LISTE                       1008
#define IDC_PLUSHAUT                    1009
#define IDC_PLUSBAS                     1010
#define IDC_MEMO                        1011
#define IDC_BUTTON3                     1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
