//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by L'Essaim.rc
//
#define IDD_DIALOG1                     101
#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define IDB_DROITE                      104
#define IDB_GAUCHE                      105
#define IDI_UNE_ABEILLE                 105
#define IDI_PLEIN_D_ABEILLES            106
#define IDI_ALEATOIRE_MOINS             107
#define IDI_ALEATOIRE_PLUS              108
#define IDI_ABEILLE_LENTE               109
#define IDI_LENT                        109
#define IDI_ABEILLE_RAPIDE              110
#define IDI_RAPIDE                      110
#define IDI_LOIN                        113
#define IDI_PRES                        114
#define IDC_NB_ABEILLES                 1000
#define IDC_ALEATOIRE                   1001
#define IDC_VITESSE                     1002
#define IDC_ATTRACTION                  1003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
