//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ControleCouleur.rc
//

#define IDS_CONTROLECOULEUR               1
#define IDS_CONTROLECOULEUR_PPG           2

#define IDS_CONTROLECOULEUR_PPG_CAPTION   100

#define IDD_PROPPAGE_CONTROLECOULEUR      100


#define IDB_CONTROLECOULEUR               1


#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_COMMAND_VALUE         32768
