//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by glougou.rc
//
#define ID_OLDTEXT                      100
#define ID_NEWTEXT                      101
#define IDB_VAGUE                       102
#define ID_AGAIN                        102
#define ID_PASSWORD                     103
#define IDB_VAGUE2                      104
#define ID_ETOLD                        104
#define IDB_VAGUE3                      105
#define ID_ETNEW                        105
#define IDB_VAGUE4                      106
#define ID_ETAGAIN                      106
#define ID_ICON                         108
#define IDI_ICON2                       109
#define IDD_DIALOG1                     110
#define IDC_NULL                        111
#define IDB_GOUTTE1                     115
#define IDI_ICON1                       116
#define IDI_ICON3                       117
#define IDC_BULLES                      1000
#define idsIsPassword                   1000
#define IDC_PROTECTION                  1001
#define idsIniFile                      1001
#define IDC_CHGMDP                      1002
#define idsScreenSaver                  1002
#define idsPassword                     1003
#define IDC_TIMER                       1004
#define idsDifferentPW                  1004
#define idsChangePW                     1005
#define IDC_PASSWORD                    1005
#define idsBadOldPW                     1006
#define IDC_VITESSE                     1006
#define idsAppName                      1007
#define IDC_GOUTTES                     1007
#define idsNoHelpMemory                 1008
#define idsHelpFile                     1009
#define IDS_MAUVAIS                     1010
#define IDB_BULLE1                      2000
#define DLG_CHANGEPASSWORD              2000
#define IDB_BULLE2                      2001
#define DLG_ENTERPASSWORD               2001
#define IDB_BULLE3                      2002
#define DLG_INVALIDPASSWORD             2002
#define IDB_ECLATE1                     2500
#define IDB_ECLATE2                     2501
#define IDB_ECLATE3                     2502
#define IDB_GOUTTE4                     2505
#define IDB_GOUTTE5                     2506
#define IDB_GOUTTE_1                    2600
#define IDB_GOUTTE_2                    2601
#define IDB_GOUTTE_3                    2602
#define IDB_GOUTTE_4                    2603
#define IDB_GOUTTE_5                    2604
#define IDB_GOUTTE_6                    2605
#define IDB_GOUTTE_7                    2606
#define IDB_GOUTTE_8                    2607
#define IDB_GOUTTE_9                    2608
#define IDB_GOUTTE_10                   2609
#define IDB_GOUTTE_11                   2610

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
