//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gridium.rc
//
#define IDD_DIALOG1                     101
#define IDI_ICON1                       105
#define IDB_ATOME                       107
#define IDB_ATOME_BRISE                 108
#define IDI_ICON2                       109
#define IDI_ICON3                       110
#define IDB_NEUTRON                     114
#define IDC_PLUSMOINS                   1000
#define IDC_CADRE                       1001
#define IDC_QUANTITE                    1002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
